/**
 * Lufora mock data — matches the UI specifications exactly.
 */

export const MOCK_USER = {
  id: "user_1",
  name: "Ada Green",
  email: "ada@lufora.app",
  avatarUrl: null,
  points: 740,
  level: 5,
  streak: 5,
  badgeCount: 4,
  plantCount: 4,
  activeJourneys: 1,
  communityPosts: 6,
  createdAt: "2025-02-10T10:00:00Z",
};

export const MOCK_PLANTS = [
  {
    id: "plant_1",
    userId: "user_1",
    name: "Monstera Deliciosa",
    species: "Monstera deliciosa",
    nickname: "Pasha",
    imageUrl: null,
    location: "indoor" as const,
    acquiredDate: "2025-01-10T00:00:00Z",
    notes: "Loves the living room corner near the window.",
    createdAt: "2025-01-10T00:00:00Z",
    latestHealthScore: 72,
    lastWatered: "2025-04-28T08:00:00Z",
    nextTask: "Water",
    nextTaskDate: "2025-05-01T08:00:00Z",
    lightNeeds: "Bright indirect",
    humidityNeeds: "Medium-High (50-60%)",
    statusNote: "Slight yellowing detected on lower leaves",
  },
  {
    id: "plant_2",
    userId: "user_1",
    name: "Snake Plant",
    species: "Sansevieria trifasciata",
    nickname: "Luna",
    imageUrl: null,
    location: "indoor" as const,
    acquiredDate: "2025-02-20T00:00:00Z",
    notes: "Very low maintenance. Office desk plant.",
    createdAt: "2025-02-20T00:00:00Z",
    latestHealthScore: 95,
    lastWatered: "2025-04-25T08:00:00Z",
    nextTask: "Check soil",
    nextTaskDate: "2025-05-05T08:00:00Z",
    lightNeeds: "Low to bright indirect",
    humidityNeeds: "Low (30-40%)",
    statusNote: null,
  },
  {
    id: "plant_3",
    userId: "user_1",
    name: "Cactus",
    species: "Echinocactus grusonii",
    nickname: "Spike",
    imageUrl: null,
    location: "balcony" as const,
    acquiredDate: "2025-03-15T00:00:00Z",
    notes: "Golden barrel cactus. South-facing window.",
    createdAt: "2025-03-15T00:00:00Z",
    latestHealthScore: 88,
    lastWatered: "2025-04-20T08:00:00Z",
    nextTask: "Check light",
    nextTaskDate: "2025-05-02T08:00:00Z",
    lightNeeds: "Full sun",
    humidityNeeds: "Low (20-30%)",
    statusNote: null,
  },
  {
    id: "plant_4",
    userId: "user_1",
    name: "Orchid",
    species: "Phalaenopsis",
    nickname: "Orchie",
    imageUrl: null,
    location: "indoor" as const,
    acquiredDate: "2025-04-01T00:00:00Z",
    notes: "Bathroom orchid. Mist weekly.",
    createdAt: "2025-04-01T00:00:00Z",
    latestHealthScore: 81,
    lastWatered: "2025-04-27T08:00:00Z",
    nextTask: "Update photo",
    nextTaskDate: "2025-04-30T08:00:00Z",
    lightNeeds: "Bright indirect",
    humidityNeeds: "High (60-80%)",
    statusNote: null,
  },
];

export const MOCK_CARE_TASKS = [
  {
    id: "task_1",
    plantId: "plant_1",
    journeyId: null,
    type: "water",
    title: "Water Monstera",
    description: "Give Pasha a thorough watering.",
    dueDate: "2025-04-30T08:00:00Z",
    completedAt: null,
    isRecurring: true,
    intervalDays: 7,
    points: 10,
    plantName: "Pasha",
  },
  {
    id: "task_2",
    plantId: "plant_3",
    journeyId: null,
    type: "check",
    title: "Check cactus light exposure",
    description: "Ensure Spike is getting enough sunlight.",
    dueDate: "2025-04-30T09:00:00Z",
    completedAt: null,
    isRecurring: false,
    intervalDays: null,
    points: 10,
    plantName: "Spike",
  },
  {
    id: "task_3",
    plantId: "plant_4",
    journeyId: null,
    type: "check",
    title: "Update orchid photo",
    description: "Take a new photo of Orchie for your growth log.",
    dueDate: "2025-04-30T10:00:00Z",
    completedAt: null,
    isRecurring: false,
    intervalDays: null,
    points: 20,
    plantName: "Orchie",
  },
  {
    id: "task_4",
    plantId: null,
    journeyId: "journey_1",
    type: "check",
    title: "Check basil seedling moisture",
    description: "Mist the basil seedlings gently.",
    dueDate: "2025-04-30T09:00:00Z",
    completedAt: null,
    isRecurring: true,
    intervalDays: 1,
    points: 5,
    plantName: "Basil",
  },
  {
    id: "task_5",
    plantId: null,
    journeyId: "journey_1",
    type: "check",
    title: "Add grow journey photo",
    description: "Take a progress photo of your basil seedling.",
    dueDate: "2025-04-30T11:00:00Z",
    completedAt: null,
    isRecurring: false,
    intervalDays: null,
    points: 15,
    plantName: "Basil",
  },
  {
    id: "task_6",
    plantId: null,
    journeyId: "journey_1",
    type: "check",
    title: "Mark first sprout",
    description: "Log the milestone when you see the first sprout.",
    dueDate: "2025-05-02T08:00:00Z",
    completedAt: null,
    isRecurring: false,
    intervalDays: null,
    points: 50,
    plantName: "Basil",
  },
  {
    id: "task_7",
    plantId: "plant_1",
    journeyId: null,
    type: "check",
    title: "Check soil moisture",
    description: "Press finger 1 inch into soil to check.",
    dueDate: "2025-04-30T07:00:00Z",
    completedAt: "2025-04-30T07:15:00Z",
    isRecurring: true,
    intervalDays: 3,
    points: 10,
    plantName: "Pasha",
  },
  {
    id: "task_8",
    plantId: "plant_1",
    journeyId: null,
    type: "prune",
    title: "Clean leaves",
    description: "Wipe dust off Monstera leaves.",
    dueDate: "2025-04-30T12:00:00Z",
    completedAt: null,
    isRecurring: false,
    intervalDays: null,
    points: 15,
    plantName: "Pasha",
  },
];

export const MOCK_JOURNEYS = [
  {
    id: "journey_1",
    userId: "user_1",
    plantName: "Basil",
    species: "Ocimum basilicum",
    imageUrl: null,
    startType: "seed" as const,
    currentStage: "seedling",
    progressPercent: 38,
    dayNumber: 12,
    pointsEarned: 95,
    status: "active" as const,
    startedAt: "2025-04-18T00:00:00Z",
    completedAt: null,
    nextMilestone: "First true leaves",
    todayTask: "Check soil moisture",
    todayTaskPoints: 10,
    estimatedNextStage: "~5 days",
    growTip: "Basil seedlings need 6-8 hours of light daily. Rotate the pot every 2 days for even growth.",
  },
];

export const MOCK_PLANT_TASKS = [
  { id: "pt_1", title: "Check soil moisture", points: 10, completed: false },
  { id: "pt_2", title: "Clean leaves", points: 15, completed: false },
  { id: "pt_3", title: "Add weekly photo", points: 20, completed: false },
];

export const MOCK_JOURNEY_TASKS = [
  { id: "jt_1", title: "Keep soil moist", points: 5, completed: true },
  { id: "jt_2", title: "Check temperature", points: 5, completed: false },
  { id: "jt_3", title: "Add photo every 3 days", points: 15, completed: false },
  { id: "jt_4", title: "Mark first sprout", points: 50, completed: false },
  { id: "jt_5", title: "Measure seedling height", points: 10, completed: false },
  { id: "jt_6", title: "Track first true leaves", points: 20, completed: false },
];

export const MOCK_JOURNEY_TIMELINE = [
  { id: "tl_1", type: "photo", label: "Starting photo", stage: "setup", day: 1, date: "2025-04-18", note: "Planted basil seeds in starter tray" },
  { id: "tl_2", type: "milestone", label: "Seeds planted", stage: "setup", day: 1, date: "2025-04-18", emoji: "🌰" },
  { id: "tl_3", type: "photo", label: "First sprout!", stage: "germination", day: 7, date: "2025-04-25", note: "Tiny green sprouts visible" },
  { id: "tl_4", type: "milestone", label: "First sprout", stage: "germination", day: 7, date: "2025-04-25", emoji: "🌱" },
  { id: "tl_5", type: "photo", label: "Seedling growing", stage: "seedling", day: 10, date: "2025-04-28", note: "Seedling is 2cm tall" },
  { id: "tl_6", type: "note", label: "Weekly progress", stage: "seedling", day: 12, date: "2025-04-30", note: "Looking healthy, slight lean toward light" },
];

export const MOCK_COMMUNITY_POSTS = [
  {
    id: "post_1",
    userId: "user_2",
    userName: "Maria Flora",
    userAvatar: null,
    title: "Why are my Monstera leaves turning yellow?",
    content: "I water once a week and keep it in indirect light. The lower leaves started yellowing last week. Is this normal or should I worry?",
    imageUrl: null,
    category: "save_my_plant",
    createdAt: "2025-04-29T14:00:00Z",
    commentCount: 12,
    likeCount: 34,
    isLiked: false,
    hasAiAnalysis: true,
  },
  {
    id: "post_2",
    userId: "user_3",
    userName: "James Root",
    userAvatar: null,
    title: "My avocado seed finally sprouted after 24 days!",
    content: "I used the toothpick method and changed the water every 3 days. Today I saw the first crack and a tiny root coming out. So excited!",
    imageUrl: null,
    category: "my_first_sprout",
    createdAt: "2025-04-28T09:00:00Z",
    commentCount: 18,
    likeCount: 67,
    isLiked: true,
    hasAiAnalysis: false,
  },
  {
    id: "post_3",
    userId: "user_4",
    userName: "Lily Bloom",
    userAvatar: null,
    title: "Is my basil seedling too leggy?",
    content: "My basil seedling is about 3 inches tall but the stem is very thin and it's leaning to one side. Should I add more light or prune it?",
    imageUrl: null,
    category: "seedling_help",
    createdAt: "2025-04-27T16:30:00Z",
    commentCount: 8,
    likeCount: 15,
    isLiked: false,
    hasAiAnalysis: true,
  },
];

export const MOCK_HEALTH_LOGS = [
  { id: "hl_1", plantId: "plant_1", score: 72, note: "Slight yellowing on lower leaves", createdAt: "2025-04-28T00:00:00Z" },
  { id: "hl_2", plantId: "plant_1", score: 78, note: null, createdAt: "2025-04-21T00:00:00Z" },
  { id: "hl_3", plantId: "plant_1", score: 82, note: "Looking good after repotting", createdAt: "2025-04-14T00:00:00Z" },
  { id: "hl_4", plantId: "plant_1", score: 86, note: null, createdAt: "2025-04-07T00:00:00Z" },
  { id: "hl_5", plantId: "plant_1", score: 90, note: "New leaf unfurling", createdAt: "2025-03-31T00:00:00Z" },
];

export const MOCK_BADGES = [
  { id: "badge_1", name: "Seedling", iconEmoji: "🌱", description: "Registered an account", earned: true, awardedAt: "2025-02-10T00:00:00Z" },
  { id: "badge_2", name: "Plant Parent", iconEmoji: "🪴", description: "Added your first plant", earned: true, awardedAt: "2025-02-11T00:00:00Z" },
  { id: "badge_3", name: "Seed Starter", iconEmoji: "🌰", description: "Started first grow journey", earned: true, awardedAt: "2025-04-18T00:00:00Z" },
  { id: "badge_4", name: "Hydration Hero", iconEmoji: "💧", description: "Completed 10 watering tasks", earned: true, awardedAt: "2025-04-25T00:00:00Z" },
  { id: "badge_5", name: "Green Thumb", iconEmoji: "🌿", description: "Reached 500 points", earned: false, awardedAt: null },
  { id: "badge_6", name: "Bloom Master", iconEmoji: "🌻", description: "Completed first Grow Journey", earned: false, awardedAt: null },
  { id: "badge_7", name: "Documenter", iconEmoji: "📸", description: "Added 10 journey photos", earned: false, awardedAt: null },
  { id: "badge_8", name: "Community Star", iconEmoji: "🏆", description: "Received 50 likes", earned: false, awardedAt: null },
  { id: "badge_9", name: "Streak Keeper", iconEmoji: "🔥", description: "7-day task streak", earned: false, awardedAt: null },
];

export const MOCK_LEADERBOARD = [
  { rank: 1, name: "Sofia Fern", points: 2340, badges: 8, tasks: 156, avatarUrl: null },
  { rank: 2, name: "Leo Vine", points: 2100, badges: 7, tasks: 142, avatarUrl: null },
  { rank: 3, name: "Rosa Bloom", points: 1890, badges: 7, tasks: 128, avatarUrl: null },
  { rank: 4, name: "Kai Moss", points: 1650, badges: 6, tasks: 115, avatarUrl: null },
  { rank: 5, name: "Ada Green", points: 740, badges: 4, tasks: 48, avatarUrl: null, isCurrentUser: true },
  { rank: 6, name: "Ivy Reed", points: 680, badges: 3, tasks: 42, avatarUrl: null },
  { rank: 7, name: "Finn Willow", points: 520, badges: 3, tasks: 35, avatarUrl: null },
  { rank: 8, name: "Mira Sage", points: 410, badges: 2, tasks: 28, avatarUrl: null },
];

export const MOCK_AI_DOCTOR_RESULT = {
  diagnosis: "Overwatering",
  confidence: "Medium",
  description: "The yellowing pattern on lower leaves is consistent with overwatering. When roots sit in excess moisture, they can't absorb nutrients properly.",
  steps: [
    "Reduce watering frequency — let top 2 inches of soil dry between waterings",
    "Check drainage holes and remove any standing water from the saucer",
    "Consider repotting with a well-draining potting mix",
    "Monitor new growth for improvement over the next 2 weeks",
  ],
};
